---
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: gaeng
    password: gaeng

  # Kakao API key 설정
kakao:
  map:
    api:
      key: 10bd665d6f227d61cfe9917682262fb9